// 定义项目 API 的 proto 文件
// protobuf 文件参考:
//  - https://developers.google.com/protocol-buffers/

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: drivers.proto

package drivers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBDriverType int32

const (
	DBDriverType_unused        DBDriverType = 0  // 占位不使用
	DBDriverType_mysql         DBDriverType = 1  // MySQL
	DBDriverType_mongo         DBDriverType = 2  // MONGODB
	DBDriverType_elasticsearch DBDriverType = 3  // ElasticSearch
	DBDriverType_redis         DBDriverType = 4  // Redis
	DBDriverType_kingbase      DBDriverType = 5  // Kingbase人大金仓
	DBDriverType_dm            DBDriverType = 6  // 达梦
	DBDriverType_shentong      DBDriverType = 7  // 神通
	DBDriverType_gbase         DBDriverType = 8  // 南大通用
	DBDriverType_vastbase      DBDriverType = 9  // 海量数据库
	DBDriverType_postgres      DBDriverType = 10 // PostgreSQL
	DBDriverType_opengauss     DBDriverType = 11 // 高斯
	DBDriverType_oceanbase     DBDriverType = 12 // OceanBase
	DBDriverType_mssql         DBDriverType = 13 // Microsoft SQL Server
	DBDriverType_oracle        DBDriverType = 14 // Oracle
	DBDriverType_highgo        DBDriverType = 15 // 瀚高数据库
)

// Enum value maps for DBDriverType.
var (
	DBDriverType_name = map[int32]string{
		0:  "unused",
		1:  "mysql",
		2:  "mongo",
		3:  "elasticsearch",
		4:  "redis",
		5:  "kingbase",
		6:  "dm",
		7:  "shentong",
		8:  "gbase",
		9:  "vastbase",
		10: "postgres",
		11: "opengauss",
		12: "oceanbase",
		13: "mssql",
		14: "oracle",
		15: "highgo",
	}
	DBDriverType_value = map[string]int32{
		"unused":        0,
		"mysql":         1,
		"mongo":         2,
		"elasticsearch": 3,
		"redis":         4,
		"kingbase":      5,
		"dm":            6,
		"shentong":      7,
		"gbase":         8,
		"vastbase":      9,
		"postgres":      10,
		"opengauss":     11,
		"oceanbase":     12,
		"mssql":         13,
		"oracle":        14,
		"highgo":        15,
	}
)

func (x DBDriverType) Enum() *DBDriverType {
	p := new(DBDriverType)
	*p = x
	return p
}

func (x DBDriverType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DBDriverType) Descriptor() protoreflect.EnumDescriptor {
	return file_drivers_proto_enumTypes[0].Descriptor()
}

func (DBDriverType) Type() protoreflect.EnumType {
	return &file_drivers_proto_enumTypes[0]
}

func (x DBDriverType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DBDriverType.Descriptor instead.
func (DBDriverType) EnumDescriptor() ([]byte, []int) {
	return file_drivers_proto_rawDescGZIP(), []int{0}
}

type OpAction int32

const (
	OpAction_unspecified OpAction = 0
	OpAction__lt         OpAction = 1
	OpAction__lte        OpAction = 2
	OpAction__eq         OpAction = 3
	OpAction__not_eq     OpAction = 4
	OpAction__gt         OpAction = 5
	OpAction__gte        OpAction = 6
	OpAction__limit      OpAction = 7
	OpAction__order_by   OpAction = 8
	OpAction__group_by   OpAction = 9
	OpAction__having     OpAction = 10
	OpAction__offset     OpAction = 11
	OpAction__like       OpAction = 12
	OpAction__not_like   OpAction = 13
)

// Enum value maps for OpAction.
var (
	OpAction_name = map[int32]string{
		0:  "unspecified",
		1:  "_lt",
		2:  "_lte",
		3:  "_eq",
		4:  "_not_eq",
		5:  "_gt",
		6:  "_gte",
		7:  "_limit",
		8:  "_order_by",
		9:  "_group_by",
		10: "_having",
		11: "_offset",
		12: "_like",
		13: "_not_like",
	}
	OpAction_value = map[string]int32{
		"unspecified": 0,
		"_lt":         1,
		"_lte":        2,
		"_eq":         3,
		"_not_eq":     4,
		"_gt":         5,
		"_gte":        6,
		"_limit":      7,
		"_order_by":   8,
		"_group_by":   9,
		"_having":     10,
		"_offset":     11,
		"_like":       12,
		"_not_like":   13,
	}
)

func (x OpAction) Enum() *OpAction {
	p := new(OpAction)
	*p = x
	return p
}

func (x OpAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpAction) Descriptor() protoreflect.EnumDescriptor {
	return file_drivers_proto_enumTypes[1].Descriptor()
}

func (OpAction) Type() protoreflect.EnumType {
	return &file_drivers_proto_enumTypes[1]
}

func (x OpAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpAction.Descriptor instead.
func (OpAction) EnumDescriptor() ([]byte, []int) {
	return file_drivers_proto_rawDescGZIP(), []int{1}
}

var File_drivers_proto protoreflect.FileDescriptor

var file_drivers_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73,
	0x2e, 0x76, 0x31, 0x2a, 0xda, 0x01, 0x0a, 0x0c, 0x44, 0x42, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x75, 0x6e, 0x75, 0x73, 0x65, 0x64, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x6d,
	0x6f, 0x6e, 0x67, 0x6f, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x72, 0x65, 0x64,
	0x69, 0x73, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x6b, 0x69, 0x6e, 0x67, 0x62, 0x61, 0x73, 0x65,
	0x10, 0x05, 0x12, 0x06, 0x0a, 0x02, 0x64, 0x6d, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x73, 0x68,
	0x65, 0x6e, 0x74, 0x6f, 0x6e, 0x67, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x67, 0x62, 0x61, 0x73,
	0x65, 0x10, 0x08, 0x12, 0x0c, 0x0a, 0x08, 0x76, 0x61, 0x73, 0x74, 0x62, 0x61, 0x73, 0x65, 0x10,
	0x09, 0x12, 0x0c, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x10, 0x0a, 0x12,
	0x0d, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x67, 0x61, 0x75, 0x73, 0x73, 0x10, 0x0b, 0x12, 0x0d,
	0x0a, 0x09, 0x6f, 0x63, 0x65, 0x61, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x10, 0x0c, 0x12, 0x09, 0x0a,
	0x05, 0x6d, 0x73, 0x73, 0x71, 0x6c, 0x10, 0x0d, 0x12, 0x0a, 0x0a, 0x06, 0x6f, 0x72, 0x61, 0x63,
	0x6c, 0x65, 0x10, 0x0e, 0x12, 0x0a, 0x0a, 0x06, 0x68, 0x69, 0x67, 0x68, 0x67, 0x6f, 0x10, 0x0f,
	0x2a, 0xb5, 0x01, 0x0a, 0x08, 0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x0a,
	0x0b, 0x75, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x5f, 0x6c, 0x74, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x5f, 0x6c, 0x74, 0x65, 0x10,
	0x02, 0x12, 0x07, 0x0a, 0x03, 0x5f, 0x65, 0x71, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x5f, 0x6e,
	0x6f, 0x74, 0x5f, 0x65, 0x71, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x5f, 0x67, 0x74, 0x10, 0x05,
	0x12, 0x08, 0x0a, 0x04, 0x5f, 0x67, 0x74, 0x65, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x5f, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x62, 0x79, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x62, 0x79, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x5f, 0x68, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x10,
	0x0a, 0x12, 0x0b, 0x0a, 0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x10, 0x0b, 0x12, 0x09,
	0x0a, 0x05, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x10, 0x0c, 0x12, 0x0d, 0x0a, 0x09, 0x5f, 0x6e, 0x6f,
	0x74, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x10, 0x0d, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_drivers_proto_rawDescOnce sync.Once
	file_drivers_proto_rawDescData = file_drivers_proto_rawDesc
)

func file_drivers_proto_rawDescGZIP() []byte {
	file_drivers_proto_rawDescOnce.Do(func() {
		file_drivers_proto_rawDescData = protoimpl.X.CompressGZIP(file_drivers_proto_rawDescData)
	})
	return file_drivers_proto_rawDescData
}

var file_drivers_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_drivers_proto_goTypes = []interface{}{
	(DBDriverType)(0), // 0: service.drivers.v1.DBDriverType
	(OpAction)(0),     // 1: service.drivers.v1.OpAction
}
var file_drivers_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_drivers_proto_init() }
func file_drivers_proto_init() {
	if File_drivers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drivers_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drivers_proto_goTypes,
		DependencyIndexes: file_drivers_proto_depIdxs,
		EnumInfos:         file_drivers_proto_enumTypes,
	}.Build()
	File_drivers_proto = out.File
	file_drivers_proto_rawDesc = nil
	file_drivers_proto_goTypes = nil
	file_drivers_proto_depIdxs = nil
}
